
@startuml
title Toga Widget Architecture

package "Interface Layer" {
    class "toga.Widget" as TogaWidget
}

package "Implementation Layer" {
    class "toga-cocoa" as Cocoa
    class "toga-gtk" as GTK
    class "toga-winforms" as WinForms
    class "toga-ios" as iOS
    class "toga-android" as Android
    class "toga-web" as Web
    class "toga-terminal" as Terminal
}

package "Native Layer" {
    class "macOS Widgets" {
    "Application"
    "Window"
    "DocumentWindow"
    "MainWindow"
    "ActivityIndicator"
    "Button"
    "Canvas"
    "DetailedList"
    "Divider"
    "ImageView"
    "Label"
    "MapView"
    "MultilineTextInput"
    "NumberInput"
    "PasswordInput"
    "ProgressBar"
    "Selection"
    "Slider"
    "Switch"
    "Table"
    "TextInput"
    "Tree"
    "WebView"
    "Widget"
    "Box"
    "ScrollContainer"
    "SplitContainer"
    "OptionContainer"
    "Camera"
    "Location"
    "Screen"
    "App Paths"
    "Command"
    "Dialogs"
    "Document"
    "Font"
    "Icon"
    "Image"
    "ListSource"
    "Source"
    "StatusIcons"
    "TreeSource"
    "Validators"
    "ValueSource"
}
class "GTK Widgets" {
    "Application"
    "Window"
    "DocumentWindow"
    "MainWindow"
    "ActivityIndicator"
    "Button"
    "Canvas"
    "DetailedList"
    "Divider"
    "ImageView"
    "Label"
    "MapView"
    "MultilineTextInput"
    "NumberInput"
    "PasswordInput"
    "ProgressBar"
    "Selection"
    "Slider"
    "Switch"
    "Table"
    "TextInput"
    "Tree"
    "WebView"
    "Widget"
    "Box"
    "ScrollContainer"
    "SplitContainer"
    "OptionContainer"
    "Location"
    "Screen"
    "App Paths"
    "Command"
    "Dialogs"
    "Document"
    "Font"
    "Icon"
    "Image"
    "ListSource"
    "Source"
    "StatusIcons"
    "TreeSource"
    "Validators"
    "ValueSource"
}
class "Windows Widgets" {
    "Application"
    "Window"
    "DocumentWindow"
    "MainWindow"
    "Button"
    "Canvas"
    "DateInput"
    "DetailedList"
    "Divider"
    "ImageView"
    "Label"
    "MapView"
    "MultilineTextInput"
    "NumberInput"
    "PasswordInput"
    "ProgressBar"
    "Selection"
    "Slider"
    "Switch"
    "Table"
    "TextInput"
    "TimeInput"
    "WebView"
    "Widget"
    "Box"
    "ScrollContainer"
    "SplitContainer"
    "OptionContainer"
    "Screen"
    "App Paths"
    "Command"
    "Dialogs"
    "Document"
    "Font"
    "Icon"
    "Image"
    "ListSource"
    "Source"
    "StatusIcons"
    "TreeSource"
    "Validators"
    "ValueSource"
}
class "iOS Widgets" {
    "Application"
    "Window"
    "MainWindow"
    "ActivityIndicator"
    "Button"
    "Canvas"
    "DetailedList"
    "Divider"
    "ImageView"
    "Label"
    "MapView"
    "MultilineTextInput"
    "NumberInput"
    "PasswordInput"
    "ProgressBar"
    "Selection"
    "Slider"
    "Switch"
    "TextInput"
    "WebView"
    "Widget"
    "Box"
    "ScrollContainer"
    "OptionContainer"
    "Camera"
    "Location"
    "Screen"
    "App Paths"
    "Dialogs"
    "Font"
    "Icon"
    "Image"
    "ListSource"
    "Source"
    "TreeSource"
    "Validators"
    "ValueSource"
}
class "Android Widgets" {
    "Application"
    "Window"
    "MainWindow"
    "Button"
    "Canvas"
    "DateInput"
    "DetailedList"
    "Divider"
    "ImageView"
    "Label"
    "MapView"
    "MultilineTextInput"
    "NumberInput"
    "PasswordInput"
    "ProgressBar"
    "Selection"
    "Slider"
    "Switch"
    "Table"
    "TextInput"
    "TimeInput"
    "WebView"
    "Widget"
    "Box"
    "ScrollContainer"
    "OptionContainer"
    "Camera"
    "Location"
    "Screen"
    "App Paths"
    "Command"
    "Dialogs"
    "Font"
    "Icon"
    "Image"
    "ListSource"
    "Source"
    "TreeSource"
    "Validators"
    "ValueSource"
}
class "Web Widgets" {
    "Application"
    "Window"
    "MainWindow"
    "ActivityIndicator"
    "Button"
    "Divider"
    "Label"
    "ProgressBar"
    "Switch"
    "TextInput"
    "Widget"
    "Box"
    "Screen"
    "Dialogs"
    "ListSource"
    "Source"
    "TreeSource"
    "Validators"
    "ValueSource"
}
class "Terminal Widgets" {
    "Application"
    "Window"
    "MainWindow"
    "Button"
    "Label"
    "TextInput"
    "Widget"
    "Box"
    "Screen"
    "App Paths"
    "Dialogs"
    "Icon"
    "ListSource"
    "Source"
    "TreeSource"
    "Validators"
    "ValueSource"
}
}

TogaWidget --> Cocoa
TogaWidget --> GTK
TogaWidget --> WinForms
TogaWidget --> iOS
TogaWidget --> Android
TogaWidget --> Web
TogaWidget --> Terminal

Cocoa --> "macOS Widgets"
GTK --> "GTK Widgets"
WinForms --> "Windows Widgets"
iOS --> "iOS Widgets"
Android --> "Android Widgets"
Web --> "Web Widgets"
Terminal --> "Terminal Widgets"

@enduml
